### ISSUE TITLE
Adding a new model using the API

### ISSUE THREAD

**Issue by HaritzPuerto** [UKP-SQuARE/square-core#103]
In https://github.com/UKP-SQuARE/square-core/tree/master/square-model-inference-api#adding-new-models-using-api
the links to upload new models use localhost. How to do it in the public app? The port seems to be different
![image](https://user-images.githubusercontent.com/2658728/155353683-42ed6da9-5972-447e-9a80-339a21adbee8.png)

Thanks!

**Comment by Rachneet** [comment]
Hey, for the public access, you just replace the ### https:.//localhost:8443 with ### https://square.ukp-lab.de
