### ISSUE TITLE
<pred: ..> in SPARQL is mistaken as html tags in  UI

### ISSUE THREAD

**Issue by HaishuoFang** [UKP-SQuARE/square-core#448]
It should be 'SELECT DISTINCT ?pv WHERE { ?e <pred:name> "TU Darmstadt" . ?e <inception> ?pv . }' but the one displayed is  'SELECT DISTINCT ?pv WHERE { ?e "TU Darmstadt" . ?e ?pv . }'

<pred:name> and <inception> is wrongly taken as html tag

**Comment by HaritzPuerto** [comment]
Hi @HaishuoFang , can I get an example of how to reproduce this? I need:
1) Screenshot of the inputs
2) Screenshot with the error

With this, I think I can reproduce it and see the source of the problem. Thanks!

**Comment by HaishuoFang** [comment]
![image](https://user-images.githubusercontent.com/28304642/222084940-9c6c880f-adc4-421e-8bfd-6e2dde339d8f.png)

![image](https://user-images.githubusercontent.com/28304642/222085058-ab9a32a4-86d6-4ddf-9d8d-464551e78185.png)

**\<pred:..\>** shouldn't be tag in html.
