### ISSUE TITLE
MetaQA should return agent idx instead of name

### ISSUE THREAD

**Issue by HaritzPuerto** [UKP-SQuARE/square-core#455]
https://github.com/UKP-SQuARE/square-core/blob/a922f5b95834d36d53bad4209b0d41053ba42863/model-inference/model_inference/tasks/inference/metaqa.py#L126

change it to
`agent_idx = idx`

and return agent_idx instead of agent_name. This will unify the output format with TWEAC

**Comment by Rachneet** [comment]
Done in the model-api-v3 branch. Will test and merge.

**Comment by HaritzPuerto** [comment]
can we merge and deploy this @Rachneet ?

**Comment by Rachneet** [comment]
There are validation errors when we change this. working to solve this.

**Comment by Rachneet** [comment]
fixed in #476
