### ISSUE TITLE
Behavioral Tests is not working

### ISSUE THREAD

**Issue by HaritzPuerto** [UKP-SQuARE/square-core#465]
when clicking on a skill, all the skills disappear

**Comment by Rachneet** [comment]
What is the exact issue? Can you explain a bit more?
We haven't changed anything there in a long time.

**Comment by HaritzPuerto** [comment]
Hi @Rachneet, it's on the UI. I just noticed but i haven't changed anything there either (it was working a few weeks ago), I still haven't checked the source of the problem

**Comment by HaritzPuerto** [comment]
fixed on #471
