### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by Danghor** [UKP-SQuARE/square-core#513]
I just found an error by randomly trying out a model.

Repro steps:
- Sign in and go to https://square.ukp-lab.de/qa_hub
- Select `HotpotQA RoBERTa Adapter`
- Click `Run`
- Click sample question `Which director lived longer, Lowell Sherman or Jonathan Kaplan?`

Expected: no error

Actual: Immediately after selecting the question, an error is shown:

<img width="1300" alt="image" src="https://github.com/UKP-SQuARE/square-core/assets/7728268/c9a3956b-d550-4e08-a40c-a8b6f3713a61">

Technical details:

Using the console, we can see this error:
<img width="1320" alt="image" src="https://github.com/UKP-SQuARE/square-core/assets/7728268/3199979e-3659-40a2-8f5e-88b60520f3a8">

Using the network tab in the developer tools shows a failed request with this summary:

```
Summary
URL: https://square.ukp-lab.de/api/skill-manager/skill/62c1ae1c536b1bb18ff91ce4/query
Status: 500
Source: Network
Address: 130.83.79.169:443 (Proxy)
Initiator: 
xhr.js:210

Request
:method: POST
:scheme: https
:authority: square.ukp-lab.de
:path: /api/skill-manager/skill/62c1ae1c536b1bb18ff91ce4/query
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 603
Content-Type: application/json
Host: square.ukp-lab.de
Origin: https://square.ukp-lab.de
Referer: https://square.ukp-lab.de/qa?skill1=62c1ae1c536b1bb18ff91ce4
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15

Response
:status: 500
Content-Length: 21
Content-Type: text/plain; charset=utf-8
Date: Tue, 12 Sep 2023 09:39:20 GMT
Server: openresty

Request Data
MIME Type: application/json
Request Data: 
```

**Comment by Rachneet** [comment]
Thank you for pointing this out. We will have a look at this.
